env = "test" # "test", "dev", "prod"

[log]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"

[server]
# The address to bind to.
port = 8080
# cert file path to enable https, example: "/etc/https/mydomain.crt"
cert_file = ""
# key file path to enable https, example: "/etc/https/mydomain.key"
key_file = ""
# The maximum number of seconds to wait for graceful shutdown.
graceful_shutdown = 60

[base]
taskbase = "http://127.0.0.1:8080"
writing = "http://127.0.0.1:8080"
